
// Objective-C API for talking to the following Go packages
//
//	github.com/dabankio/wallet-core/core/bbc
//	github.com/dabankio/wallet-core/bip44
//	github.com/dabankio/wallet-core/bip39
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bbc_FRAMEWORK_H__
#define __Bbc_FRAMEWORK_H__

#include "Bbc.objc.h"
#include "Bip44.objc.h"
#include "Bip39.objc.h"
#include "Universe.objc.h"

#endif
